dl3/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from login.views import index, signin, signup

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", index, name="index"),
    path("index/", index, name="index"),
    path("signup/", signup, name="signup"),
    path("signin/<str:user_name>", signin, name="signin"),
    path("signin/", signin, name="signin"),
    path("main/", include("main.urls")),
    url(r"mdeditor/", include("mdeditor.urls")),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import include, path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="main"),
    path("<str:option>", views.index, name="main"),
]

tdb/models.py
from django.db import models

# Create your models here.
import os

import shutil

from runner.models import TrainRunner, TestRunner
import sh
from django.db import models


from login.models import User
# from port.models import Port


# Create your models here.
class TDB(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    TrainRunner = models.ForeignKey(TrainRunner, on_delete=models.CASCADE, null=True)
    TestRunner = models.ForeignKey(TestRunner, on_delete=models.CASCADE, null=True)
    port = models.IntegerField(unique=True)
    pid = models.IntegerField()
    name = models.CharField(max_length=200)
    link = models.URLField()
    cache_dir = models.CharField(max_length=200)

    def delete(self, using=False, keep_parents=False):
        print("Delete tensorboard", self.port)
        os.system(f"kill -9 {self.pid}")
        shutil.rmtree(self.cache_dir)
        return super().delete(using=using, keep_parents=keep_parents)

main/views.py
from django.shortcuts import render
from login.models import User
from utils import get_gpu_info
from django.http import HttpResponseRedirect
from django.urls import reverse
from filelist.views import view_filelist
from tdb.views import view_tdb
from runner.views import view_runner
view_fn = dict(
    gpu=lambda request, user: {"gpu_info": get_gpu_info()},
    config=lambda request, user: view_filelist(request, user, "config"),
    record=lambda request, user: view_filelist(request, user, "record"),
    tdb=view_tdb,
    process=view_runner,
)


# Create your views here.
def index(request, option="gpu"):
    if option == "gpu":
        return render(request, "main/gpu.html", view_fn["gpu"](None, None))
    if "user_name" in request.COOKIES:
        user_name = request.COOKIES["user_name"]
    else:
        return HttpResponseRedirect(reverse("signin"))
    try:
        user = User.objects.get(name=user_name)
    except:
        return HttpResponseRedirect(reverse("signin"))
    if option in view_fn:
        context = view_fn[option](request, user=user)
        template = f"main/{option}.html"
    else:
        context = {"error": f"not find context about option {option}"}
        template = f"main/main.html"
    context["user_name"] = user_name
    if 'jump_to' in context:
        return HttpResponseRedirect(context['jump_to'])
    return render(request, template, context)

tdb/views.py
import os
import os.path as osp

# Create your views here.
from typing import List

import sh
from django.http import HttpRequest
from login.models import User
from utils.info_port import Port
from utils.info_env import get_cache_dir, get_host_ip

from .models import TDB


def create_tdb(parent: User, paths: List[str]) -> TDB:
    cache_root = get_cache_dir()
    port = Port.get_avaliable_port()
    cache_dir = osp.join(cache_root, f"tdb:{port}")
    if osp.isdir(cache_dir):
        print("remove", cache_dir)
        sh.rm("-rf", cache_dir)
    os.mkdir(cache_dir)
    name = "<br>".join(osp.basename(p) for p in paths)
    link = f"{get_host_ip()}:{port}"
    for path in paths:
        sh.ln("-s", path, osp.join(cache_dir, osp.basename(path)))
    p = sh.tensorboard(
        f"--logdir={cache_dir}",
        "--bind_all",
        "--samples_per_plugin=images=1000",
        f"--port={port}",
        _bg=True,
    )
    tdb = parent.tdb_set.create(
        port=port, pid=p.pid, name=name, link=link, cache_dir=cache_dir
    )
    tdb.save()
    return tdb


def close_tdb(port):
    if TDB.objects.filter(port=port).exists():
        TDB.objects.filter(port=port).first().delete()


def close_all_user_tdb(user):
    for q in user.tdb_set.all():
        q.delete()


def view_tdb(request: HttpRequest, user: User):
    if "close_all" in request.POST:
        close_all_user_tdb(user)
    tdbs = user.tdb_set.all()
    return {"TDBs": tdbs}

main/templates/main/config.html
{% extends "main/main.html" %}
{% block menu %}
<style>
    #config {
        background-color: brown;
    }
</style>
{{block.super}}
{% endblock %}
{% block content %}
{% include "components/filelist.html" %}
{% endblock %}

main/templates/main/gpu.html
{% extends "main/main.html" %}
{% block menu %}
<meta http-equiv="refresh" content="4">
<style>
    #gpu {
        background-color: brown;
    }

    #gpu_window {
        width: fit-content;
        margin: auto;
        text-align: left;
    }
</style>
{{block.super}}
{% endblock %}
{%block content%}
<div id=gpu_window>
    {{gpu_info|safe}}
</div>
{%endblock%}

main/templates/main/main.html
{% extends "base/base.html" %}
{% block menu%}
<li><a href='{% url "main:main" "config" %}' id=config>配置文件</a></li>
<li><a href='{% url "main:main" "record" %}' id=record>记录文件</a></li>
<li><a href='{% url "main:main" "gpu" %}' id=gpu>GPU状态</a></li>
<li><a href='{% url "main:main" "tdb" %}' id=tdb>Tensorboards</a></li>
<li><a href='https://docs.qq.com/' target='_blank'>腾讯文档</a></li>
<li><a href='{% url "main:main" "process" %}' id=process>进程</a></li>

{% endblock %}
{% block debug_info %}
{% if error %}
{{error}}
{% endif %}
{% endblock %}

main/templates/main/process.html
{% extends "main/main.html" %} {% block menu %}
<style>
  #process {
    background-color: brown;
  }
</style>
{{block.super}} {% endblock %} 
{% block content%}
{% include "components/runner.html" %} 
{% endblock %}

main/templates/main/record.html
{% extends "main/main.html" %} {% block menu %}
<style>
  #record {
    background-color: brown;
  }
</style>
{{block.super}}
 {% endblock %} 
 {% block content %}
 {% include "components/filelist.html" %}
 {% endblock %}

main/templates/main/tdb.html
{% extends "main/main.html" %}
{% block menu %}
<style>
    #tdb {
        background-color: brown;
    }
</style>
{{block.super}}
{% endblock %}
{% block content %}

<body>
    <form method="post" action="">
        {% csrf_token %}
        <button type="submit" name="close_all">
            Close all
        </button>
    </form>
    <table>
        <tr>
            <th class="firstcol">Name</th>
            <th>port</th>
        </tr>
        {% if TDBs %}
        <ul>
            {% for TDB in TDBs %}
            <tr>
                <td class="firstcol">
                    <a href="//{{TDB.link}}" target='_blank'>
                        <div class="menu">
                            {{TDB.name|safe}}
                        </div>
                    </a>
                    </button>
                </td>
                <td>{{TDB.port}}</td>
            </tr>
            {% endfor %}
        </ul>
        {% endif %}
    </table>
    
</body>
{% endblock %}